apiVersion: apps/v1
kind: deployment
metadata:
 name: my-app
spec:
 replics: 2
 selector:
  matchlabels:
   app: my-app
 template:
  metadata:
   labels:
    app: my-app
  spec:
   cpntainers:
   - name: myapp-container
     image: santrajrakesh/employee-app
     ports:
     - containerPort: 9092
  